#!/usr/bin/env bash
set -e
SKILL_DIR="$HOME/.claude/skills/setup-project"
mkdir -p "$SKILL_DIR"
cp "$(dirname "$0")/SKILL.md" "$SKILL_DIR/SKILL.md"
echo ""
echo "============================================================"
echo "  Claude Dev Toolkit installed!"
echo "============================================================"
echo ""
echo "  USAGE:"
echo "  Open Claude Code in any project directory and type:"
echo ""
echo "    /setup-project"
echo ""
echo "  This single command installs and configures:"
echo "    Phase 1: Knowledge Graph  (understand codebase)"
echo "    Phase 2: Site Optimizer   (UX audit + PM analysis)"
echo "    Phase 3: Frontend QA      (auto-test on code change)"
echo "    Phase 4: Integration      (hooks + MCP + CLAUDE.md)"
echo ""
echo "============================================================"
echo ""
